In [1]:
# Importando a biblioteca
import pandas as pd

In [2]:
# Definindo o caminho do arquivo
arquivo = '../datasets/sodium-table-categorized.xlsx'

In [3]:
# Lendo a planilha
df = pd.read_excel(arquivo)

In [4]:
# Renomeando as variáveis que serão consideradas para a construção da tabela cruzada
var1 = "Quantidade Sodium OMS"
var2 = "Menu_Category"

In [5]:
# Exibindo as 5 primeiras observações do Data Set
df.head()

,Menu_Category,Menu Items,peso,energia,proteina,gord_total,gord_saturada,gord_trans,colesterol,carboidratos,total_acucar,Added_Sugars,Sodium,Quantidade Sodium OMS
0,Regular Menu,McVeggie™ Burger,168 g,40205,1024,1383,534,16,249,5654,79,449,70613,nao aceitavel
1,Regular Menu,McAloo Tikki Burger®,146 g,33952,85,1131,427,2,147,5027,705,407,54534,nao aceitavel
2,Regular Menu,McSpicy™ Paneer Burger,199 g,65276,2029,3945,1712,18,2185,5233,835,527,107458,nao aceitavel
3,Regular Menu,Spicy Paneer Wrap,250 g,67468,2096,391,1973,26,4093,5927,35,108,108746,nao aceitavel
4,Regular Menu,American Veg Burger,177 g,51217,153,2345,1051,17,2524,5696,785,476,105124,nao aceitavel

#Tabela Cruzada com frequências absolutas

In [6]:
# Contruindo a tabela cruzada com frequências absolutas
df_tabela_cruz = pd.crosstab(df[var1], df[var2], margins=True)

In [7]:
# A tabela cruzada é construída com uma coluna total e uma linha total escritas em inglês
df_tabela_cruz

Menu_Category,Beverages Menu,Breakfast Menu,Condiments Menu,Desserts Menu,Gourmet Menu,McCafe Menu,Regular Menu,All
Quantidade Sodium OMS,,,,,,,,
aceitavel,4,4,3,1,0,14,2,28
nao aceitavel,13,11,6,1,10,37,34,112
All,17,15,9,2,10,51,36,140

In [8]:
# Podemos renomear a coluna All para o Português:
df_tabela_cruz.rename(columns={'All': 'Total'}, inplace=True)
# Podemos renomear a linha All para o Português:
df_tabela_cruz.rename(index={'All': 'Total'}, inplace=True)

In [9]:
df_tabela_cruz

Menu_Category,Beverages Menu,Breakfast Menu,Condiments Menu,Desserts Menu,Gourmet Menu,McCafe Menu,Regular Menu,Total
Quantidade Sodium OMS,,,,,,,,
aceitavel,4,4,3,1,0,14,2,28
nao aceitavel,13,11,6,1,10,37,34,112
Total,17,15,9,2,10,51,36,140

In [10]:
# Tabela Cruzada com frequências relativas (% do Total)
df_tabela_cruz_porcentagem = (pd.crosstab(
    df[var1], df[var2], margins=True, normalize=True)*100).round(1)
df_tabela_cruz_porcentagem

Menu_Category,Beverages Menu,Breakfast Menu,Condiments Menu,Desserts Menu,Gourmet Menu,McCafe Menu,Regular Menu,All
Quantidade Sodium OMS,,,,,,,,
aceitavel,2.9,2.9,2.1,0.7,0.0,10.0,1.4,20.0
nao aceitavel,9.3,7.9,4.3,0.7,7.1,26.4,24.3,80.0
All,12.1,10.7,6.4,1.4,7.1,36.4,25.7,100.0

In [11]:
# Podemos renomear a linha All e a coluna All para o Português:
df_tabela_cruz_porcentagem.rename(index={'All': 'Total'}, inplace=True)
df_tabela_cruz_porcentagem.rename(columns={'All': 'Total'}, inplace=True)

In [12]:
df_tabela_cruz_porcentagem

Menu_Category,Beverages Menu,Breakfast Menu,Condiments Menu,Desserts Menu,Gourmet Menu,McCafe Menu,Regular Menu,Total
Quantidade Sodium OMS,,,,,,,,
aceitavel,2.9,2.9,2.1,0.7,0.0,10.0,1.4,20.0
nao aceitavel,9.3,7.9,4.3,0.7,7.1,26.4,24.3,80.0
Total,12.1,10.7,6.4,1.4,7.1,36.4,25.7,100.0

In [13]:
# Tabela Cruzada com frequências relativas nas linhas (% da Linha)
df_tabela_cruz_porcentagem_linhas = (pd.crosstab(
    df[var1], df[var2], margins=True, normalize='index')*100).round(1)
df_tabela_cruz_porcentagem_linhas

Menu_Category,Beverages Menu,Breakfast Menu,Condiments Menu,Desserts Menu,Gourmet Menu,McCafe Menu,Regular Menu
Quantidade Sodium OMS,,,,,,,
aceitavel,14.3,14.3,10.7,3.6,0.0,50.0,7.1
nao aceitavel,11.6,9.8,5.4,0.9,8.9,33.0,30.4
All,12.1,10.7,6.4,1.4,7.1,36.4,25.7

In [14]:
# Podemos renomear a linha All para o Português:
df_tabela_cruz_porcentagem_linhas.rename(index={'All': 'Total'}, inplace=True)

In [15]:
df_tabela_cruz_porcentagem_linhas

Menu_Category,Beverages Menu,Breakfast Menu,Condiments Menu,Desserts Menu,Gourmet Menu,McCafe Menu,Regular Menu
Quantidade Sodium OMS,,,,,,,
aceitavel,14.3,14.3,10.7,3.6,0.0,50.0,7.1
nao aceitavel,11.6,9.8,5.4,0.9,8.9,33.0,30.4
Total,12.1,10.7,6.4,1.4,7.1,36.4,25.7

In [16]:
# Tabela Cruzada com frequências relativas nas colunas (% da Coluna)
df_tabela_cruz_porcentagem_colunas = (pd.crosstab(
    df[var1], df[var2], margins=True, normalize='columns')*100).round(1)
df_tabela_cruz_porcentagem_colunas

Menu_Category,Beverages Menu,Breakfast Menu,Condiments Menu,Desserts Menu,Gourmet Menu,McCafe Menu,Regular Menu,All
Quantidade Sodium OMS,,,,,,,,
aceitavel,23.5,26.7,33.3,50.0,0.0,27.5,5.6,20.0
nao aceitavel,76.5,73.3,66.7,50.0,100.0,72.5,94.4,80.0

In [17]:
# Podemos renomear a coluna All para o Português:
df_tabela_cruz_porcentagem_colunas.rename(
    columns={'All': 'Total'}, inplace=True)

In [18]:
df_tabela_cruz_porcentagem_colunas

Menu_Category,Beverages Menu,Breakfast Menu,Condiments Menu,Desserts Menu,Gourmet Menu,McCafe Menu,Regular Menu,Total
Quantidade Sodium OMS,,,,,,,,
aceitavel,23.5,26.7,33.3,50.0,0.0,27.5,5.6,20.0
nao aceitavel,76.5,73.3,66.7,50.0,100.0,72.5,94.4,80.0

# INTERPRETANDO OS RESULTADOS

Com base nas tabelas geradas anteriormente e mostradas a seguir, podemos observar por exemplo,que:

- **10,7%** dos itens do Menu fazem parte da Categoria Breakfast Menu (tabela cruzada exibida com as frequências relativas (porcentagens) -df_tabela_cruz_porcentagem)
- **20%** dos itens do Menu possuem nível de sódio aceitável (tabela cruzada exibida com as frequências relativas (porcentagens) -df_tabela_cruz_porcentagem)
- **Nenhum (0%)** item do Menu Gourmet possui nível de sódio aceitável _OU_ **Nenhum (0%)** item com nível de sódio aceitável é do Menu Gourmet (tabela cruzada exibida com as frequências relativas (porcentagens)-df_tabela_cruz_porcentagem)
- **0,9%** dos itens que possuem nível não aceitável de sódio são do Menu Desserts (sobremesa) (tabela cruzada exibida com frequências relativas por linhas -df_tabela_cruz_porcentagem_linhas).
- **Dentre** os itens com nível de sódio aceitável, 50% são do Menu McCafe (tabela cruzada exibida com as frequências relativas (porcentagens) por linhas -df_tabela_cruz_porcentagem_linhas)
- **Dentre** os itens do Menu Desserts (sobremesa), 50% tem nível de sódio aceitável (tabela cruzada exibida com as frequências relativas (porcentagens) por colunas -df_tabela_cruz_porcentagem_colunas)
- **94,4%** dos itens do Meu Regular possuem nível não aceitável de sódio(tabela cruzada exibida com frequências relativas (porcentagens) por colunas -df_tabela_cruz_porcentagem_colunas).

In [19]:
df_tabela_cruz

Menu_Category,Beverages Menu,Breakfast Menu,Condiments Menu,Desserts Menu,Gourmet Menu,McCafe Menu,Regular Menu,Total
Quantidade Sodium OMS,,,,,,,,
aceitavel,4,4,3,1,0,14,2,28
nao aceitavel,13,11,6,1,10,37,34,112
Total,17,15,9,2,10,51,36,140

In [20]:
df_tabela_cruz_porcentagem

Menu_Category,Beverages Menu,Breakfast Menu,Condiments Menu,Desserts Menu,Gourmet Menu,McCafe Menu,Regular Menu,Total
Quantidade Sodium OMS,,,,,,,,
aceitavel,2.9,2.9,2.1,0.7,0.0,10.0,1.4,20.0
nao aceitavel,9.3,7.9,4.3,0.7,7.1,26.4,24.3,80.0
Total,12.1,10.7,6.4,1.4,7.1,36.4,25.7,100.0

In [21]:
df_tabela_cruz_porcentagem_linhas

Menu_Category,Beverages Menu,Breakfast Menu,Condiments Menu,Desserts Menu,Gourmet Menu,McCafe Menu,Regular Menu
Quantidade Sodium OMS,,,,,,,
aceitavel,14.3,14.3,10.7,3.6,0.0,50.0,7.1
nao aceitavel,11.6,9.8,5.4,0.9,8.9,33.0,30.4
Total,12.1,10.7,6.4,1.4,7.1,36.4,25.7

In [22]:
df_tabela_cruz_porcentagem_colunas

Menu_Category,Beverages Menu,Breakfast Menu,Condiments Menu,Desserts Menu,Gourmet Menu,McCafe Menu,Regular Menu,Total
Quantidade Sodium OMS,,,,,,,,
aceitavel,23.5,26.7,33.3,50.0,0.0,27.5,5.6,20.0
nao aceitavel,76.5,73.3,66.7,50.0,100.0,72.5,94.4,80.0

In [23]:
# Salvando as tabelas cruzadas em arquivo de planilha Excel
writer = pd.ExcelWriter('Tabelas_Cruzadas.xlsx')
df_tabela_cruz.to_excel(writer, sheet_name="Tab_cruz_abs", index=True)
df_tabela_cruz_porcentagem.to_excel(
    writer, sheet_name="Tab_Cruzada_porc", index=True)
df_tabela_cruz_porcentagem_linhas.to_excel(
    writer, sheet_name="Tab_Cruzada_porc_linhas", index=True)
df_tabela_cruz_porcentagem_colunas.to_excel(
    writer, sheet_name="Tab_Cruzada_porc_colunas", index=True)
writer.close()

In [24]:
# Exibe o conteúdo de todas as planilhas do arquivo Excel
arquivo_tabelas = "Tabelas_Cruzadas.xlsx"
xls = pd.ExcelFile(arquivo_tabelas)

for nome_planilha in xls.sheet_names:
    print(f"\n--- {nome_planilha} ---")
    display(pd.read_excel(arquivo_tabelas, sheet_name=nome_planilha, index_col=0))

--- Tab_cruz_abs ---

,Beverages Menu,Breakfast Menu,Condiments Menu,Desserts Menu,Gourmet Menu,McCafe Menu,Regular Menu,Total
Quantidade Sodium OMS,,,,,,,,
aceitavel,4,4,3,1,0,14,2,28
nao aceitavel,13,11,6,1,10,37,34,112
Total,17,15,9,2,10,51,36,140

--- Tab_Cruzada_porc ---

,Beverages Menu,Breakfast Menu,Condiments Menu,Desserts Menu,Gourmet Menu,McCafe Menu,Regular Menu,Total
Quantidade Sodium OMS,,,,,,,,
aceitavel,2.9,2.9,2.1,0.7,0.0,10.0,1.4,20
nao aceitavel,9.3,7.9,4.3,0.7,7.1,26.4,24.3,80
Total,12.1,10.7,6.4,1.4,7.1,36.4,25.7,100

--- Tab_Cruzada_porc_linhas ---

,Beverages Menu,Breakfast Menu,Condiments Menu,Desserts Menu,Gourmet Menu,McCafe Menu,Regular Menu
Quantidade Sodium OMS,,,,,,,
aceitavel,14.3,14.3,10.7,3.6,0.0,50.0,7.1
nao aceitavel,11.6,9.8,5.4,0.9,8.9,33.0,30.4
Total,12.1,10.7,6.4,1.4,7.1,36.4,25.7

--- Tab_Cruzada_porc_colunas ---

,Beverages Menu,Breakfast Menu,Condiments Menu,Desserts Menu,Gourmet Menu,McCafe Menu,Regular Menu,Total
Quantidade Sodium OMS,,,,,,,,
aceitavel,23.5,26.7,33.3,50,0,27.5,5.6,20
nao aceitavel,76.5,73.3,66.7,50,100,72.5,94.4,80