In [1]:
import math
import pandas as pd

In [2]:
df = pd.read_excel('../datasets/project-1.xlsx')
df

   Escolaridade  Sexo  Idade
0      superior   fem     21
1      superior  masc     28
2   fundamental  masc     13
3         médio  masc     19
4         médio   fem     19
5      superior   fem     27
6   fundamental  masc     16
7         médio   fem     23
8   fundamental   fem     15
9      superior  masc     23
10        médio  masc     23
11     superior   fem     22
12  fundamental   fem     20
13        médio  masc     19
14     superior  masc     22
15        médio   fem     18

In [3]:
df.Idade.value_counts().sort_index()

Idade
13    1
15    1
16    1
18    1
19    3
20    1
21    1
22    2
23    3
27    1
28    1
Name: count, dtype: int64

In [4]:
total = df.Idade.value_counts().sum()

In [5]:
quantitative_data = pd.DataFrame(df)
quantitative_data = quantitative_data.groupby(
    'Idade').size().reset_index(name='counts')

In [6]:
quantitative_data["Frequency %"] = round(
    quantitative_data['counts'] * 100 / total, 2)
quantitative_data

    Idade  counts  Frequency %
0      13       1         6.25
1      15       1         6.25
2      16       1         6.25
3      18       1         6.25
4      19       3        18.75
5      20       1         6.25
6      21       1         6.25
7      22       2        12.50
8      23       3        18.75
9      27       1         6.25
10     28       1         6.25

In [7]:
quantitative_data["Acumulative Frequency %"] = quantitative_data['Frequency %'].cumsum()
quantitative_data

    Idade  counts  Frequency %  Acumulative Frequency %
0      13       1         6.25                     6.25
1      15       1         6.25                    12.50
2      16       1         6.25                    18.75
3      18       1         6.25                    25.00
4      19       3        18.75                    43.75
5      20       1         6.25                    50.00
6      21       1         6.25                    56.25
7      22       2        12.50                    68.75
8      23       3        18.75                    87.50
9      27       1         6.25                    93.75
10     28       1         6.25                   100.00